version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: ember-source
    versions:
    - 3.24.0
    - 3.24.1
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.1
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
